// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NetworkClientAPI.Migrations
{
    [DbContext(typeof(NetworkClientDb))]
    [Migration("20250226010905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("NetworkClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mac")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NetworkClients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ip = "192.168.0.11",
                            IsActive = false,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Ip = "192.168.0.21",
                            IsActive = true,
                            Name = "Sons computer"
                        },
                        new
                        {
                            Id = 3,
                            Ip = "192.168.0.34",
                            IsActive = false,
                            Name = "Dogs Steam Deck"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
